development:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: esparratacus
  password: techspec1987
  database: cinemapi_development

test:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: postgres
  database: cinemapi_test

production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: postgres
  database: cinemapi_production
